
CREATE TABLE USUARIOS (
    CODUSUARIO VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    DATA_CRIADO DATE NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1),
    NASCIMENTO DATE,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(60) NOT NULL,
    PAGINOMETRO INTEGER NOT NULL,
	PRIMARY KEY (CODUSUARIO)
);
ALTER TABLE USUARIOS 
	ADD CONSTRAINT CHECK_SEXO
		CHECK ( SEXO IN ('F','M','O'));
 ALTER TABLE USUARIOS        
	ADD CONSTRAINT CHECK_UF
		CHECK ( ESTADO IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA',
						   'PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO')
				);
				

CREATE TABLE LIVROS (
    CODLIVRO INTEGER NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    SUB_TITULO VARCHAR(100),
    SINOPSE VARCHAR(1000) NOT NULL,
    NRO_PAGINAS SMALLINT NOT NULL,
    NOTA NUMERIC NOT NULL,
	PRIMARY KEY (CODLIVRO)
);
ALTER TABLE LIVROS ADD CONSTRAINT CHECK_NOTA
	CHECK (NOTA BETWEEN 0 AND 5);
	
ALTER TABLE LIVROS ADD CONSTRAINT TAMANHO_ISBN
		CHECK (LENGTH(ISBN) = 13);
		
CREATE TABLE SIMILARIDADES (
	CODSS INTEGER NOT NULL,
	CODLIVRO1 INTEGER NOT NULL,
	CODLIVRO2 INTEGER NOT NULL,
	PRIMARY KEY (CODSS),
	FOREIGN KEY (CODLIVRO1) REFERENCES LIVROS (CODLIVRO) ON DELETE CASCADE,
	FOREIGN KEY (CODLIVRO2) REFERENCES LIVROS (CODLIVRO) ON DELETE CASCADE
);

CREATE TABLE AUTORES (
    CODAUTOR INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE,
    BIBLIOGRAFIA VARCHAR(1000),
    PAIS VARCHAR(40),
    ESTADO VARCHAR(40),
    CIDADE VARCHAR(40),
	PRIMARY KEY (CODAUTOR)
);

CREATE TABLE EDITORAS (
    CODEDITORA INTEGER NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    DESCRICAO VARCHAR(1000),
	PRIMARY KEY (CODEDITORA)
);

CREATE TABLE PUBLICACOES1 (
    LIVROP INTEGER NOT NULL,
    AUTORP INTEGER NOT NULL,
    PRIMARY KEY (LIVROP, AUTORP),
	FOREIGN KEY (LIVROP) REFERENCES LIVROS (CODLIVRO) ON DELETE CASCADE,
	FOREIGN KEY (AUTORP) REFERENCES AUTORES (CODAUTOR) ON DELETE CASCADE
);

CREATE TABLE PUBLICACOES2 (
    LIVROP INTEGER NOT NULL,
    EDITORAP INTEGER NOT NULL,
    PRIMARY KEY (LIVROP, EDITORAP),
	FOREIGN KEY (LIVROP) REFERENCES LIVROS (CODLIVRO) ON DELETE CASCADE,
	FOREIGN KEY (EDITORAP) REFERENCES EDITORAS (CODEDITORA) ON DELETE CASCADE
);
	
CREATE TABLE INTERACOES2 (
    EDITORAP INTEGER NOT NULL,
    AUTORP INTEGER NOT NULL,
    PRIMARY KEY (EDITORAP, AUTORP),
	FOREIGN KEY (EDITORAP) REFERENCES EDITORAS (CODEDITORA),
	FOREIGN KEY (AUTORP) REFERENCES AUTORES (CODAUTOR)
);

CREATE TABLE GRUPOS (
    CODGRUPO INTEGER NOT NULL,
    MODGRUPO VARCHAR(16) NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    DATA DATE NOT NULL,
    DESC_GRUPO VARCHAR(1000),
	PRIMARY KEY (CODGRUPO),
	FOREIGN KEY (MODGRUPO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE
);

CREATE TABLE TOPICOS (
    CODTOPICO INTEGER NOT NULL,
    CODGRUPO INTEGER NOT NULL,
    CODUSUARIO VARCHAR(16) NOT NULL,
    TITULO VARCHAR(60) NOT NULL,
    TEXTO VARCHAR(1000) NOT NULL,
    CRIACAO TIMESTAMP NOT NULL,
    PRIMARY KEY (CODTOPICO),
	FOREIGN KEY (CODGRUPO) REFERENCES GRUPOS (CODGRUPO) ON DELETE CASCADE,
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE
);

CREATE TABLE MENSAGENS (
    CODMSG INTEGER NOT NULL,
    CODTOPICO INTEGER NOT NULL,
    CODUSUARIO VARCHAR(16) NOT NULL,
    TEXTOMSG VARCHAR(1000) NOT NULL,
    CRIACAO TIMESTAMP NOT NULL,
    PRIMARY KEY (CODMSG),
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE,
	FOREIGN KEY (CODTOPICO) REFERENCES TOPICOS (CODTOPICO) ON DELETE CASCADE
);

CREATE TABLE ESTANTES (
    CODESTANTE INTEGER NOT NULL,
    CODUSUARIO VARCHAR(16)NOT NULL,
    CODLIVRO INTEGER NOT NULL,
	STATUS_LEITURA VARCHAR(9) NOT NULL,
    NOTA NUMBER,
    MODELO CHAR(2) NOT NULL,
    FAVORITO VARCHAR(3) NOT NULL,
    TROCO VARCHAR(3) NOT NULL,
    TIPO CHAR(2) NOT NULL,
	PRIMARY KEY (CODESTANTE),
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO),
	FOREIGN KEY (CODLIVRO) REFERENCES LIVROS (CODLIVRO) 
	);
ALTER TABLE ESTANTES 
	ADD CONSTRAINT CHECK_STATUS
		CHECK (STATUS_LEITURA IN
			('QUERO LER', 'LIDO', 'LENDO', 'RELENDO', 'ABANDONEI')
		);		
ALTER TABLE ESTANTES 
	ADD CONSTRAINT CHECK_MODELO
		CHECK (MODELO IN
			('PA','EB','AB')
		);		
ALTER TABLE ESTANTES 
	ADD CONSTRAINT CHECK_TIPO
		CHECK (TIPO IN
			('LV','HQ','RV')
		);	
ALTER TABLE ESTANTES 
	ADD CONSTRAINT CHECK_FAV
		CHECK (FAVORITO IN
			('YES','NO')
		);
ALTER TABLE ESTANTES 
	ADD CONSTRAINT CHECK_TROCO
		CHECK (TROCO IN
			('YES','NO')
		);
		

CREATE TABLE USUARIOS_PLUS (
	CODUSUARIO VARCHAR(16) NOT NULL,
    CEP CHAR(8) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(60) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
	COMPLEMENTO VARCHAR(6) NOT NULL,
    CREDITO SMALLINT NOT NULL,
    COR CHAR(2) NOT NULL,
    QNT_NEGATIVA SMALLINT NOT NULL,
    QNT_NEUTRA SMALLINT NOT NULL,
    QNT_POSITIVA SMALLINT NOT NULL,
    PRIMARY KEY (CODUSUARIO),
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE
);
ALTER TABLE USUARIOS_PLUS ADD CONSTRAINT CHECK_COR
	CHECK (COR IN ('AM','AZ'));

	
CREATE TABLE TROCAS (
    CODS INTEGER NOT NULL,
	SITUACAO VARCHAR(10) NOT NULL,
    NRO_CREDITOS SMALLINT NOT NULL,
    COMENTARIO VARCHAR(200),
    DATA_SOLICITACAO DATE,
    NEUTRA VARCHAR(3),
    NEGATIVA VARCHAR(3),
    POSITIVA VARCHAR(3),
    USUARIODONO VARCHAR(16) NOT NULL,
    USUARIOSLC VARCHAR(16) NOT NULL,
    CODESTANTE INTEGER NOT NULL,
    PRIMARY KEY (CODS),
	FOREIGN KEY (USUARIODONO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE,
	FOREIGN KEY (USUARIOSLC) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE,
	FOREIGN KEY (CODESTANTE) REFERENCES ESTANTES (CODESTANTE) ON DELETE CASCADE
);
ALTER TABLE TROCAS
	ADD CONSTRAINT CHECK_SITUACAO
		CHECK (SITUACAO IN
			('AGUARDANDO','ACEITA','CANCELADA','RECUSADA')
		);	
ALTER TABLE TROCAS 
	ADD CONSTRAINT CHECK_NEUTRA
		CHECK (NEUTRA IN
			('YES','NO')
		);		
ALTER TABLE TROCAS 
	ADD CONSTRAINT CHECK_NEG
		CHECK (NEGATIVA IN
			('YES','NO')
		);
ALTER TABLE TROCAS 
	ADD CONSTRAINT CHECK_POS
		CHECK (POSITIVA IN
			('YES','NO')
		);
ALTER TABLE TROCAS
	ADD CONSTRAINT CHECK_CREDITOS
		CHECK (NRO_CREDITOS BETWEEN 1 AND 2);


CREATE TABLE RECADOS (
    CODRECADO INTEGER NOT NULL,
    MENSAGEM VARCHAR(1000) NOT NULL,
    CRIACAO TIMESTAMP NOT NULL,
    CODUSUARIOE VARCHAR(16) NOT NULL,
    CODUSUARIOR VARCHAR(16) NOT NULL,
    PRIMARY KEY (CODRECADO, CODUSUARIOE),
	FOREIGN KEY (CODUSUARIOE) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE,
	FOREIGN KEY (CODUSUARIOR) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE
);

CREATE TABLE HISTORICOS (
	CODHIST INTEGER NOT NULL,
    COMENTARIO VARCHAR(200),
    NRO_PAGINAS VARCHAR(4) NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    SPOILER VARCHAR(3) NOT NULL,
    ESTANTE INTEGER NOT NULL,
	PRIMARY KEY (CODHIST, ESTANTE),
	FOREIGN KEY (ESTANTE) REFERENCES ESTANTES (CODESTANTE) ON DELETE CASCADE
);	
ALTER TABLE HISTORICOS 
	ADD CONSTRAINT CHECK_SPOILER
		CHECK (SPOILER IN
			('YES','NO')
		);


CREATE TABLE RESENHAS (
    SPOILER VARCHAR(3) NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    TITULO VARCHAR(60) NOT NULL,
    TEXTO VARCHAR(1000) NOT NULL,
    ESTANTE INTEGER NOT NULL,
	FOREIGN KEY (ESTANTE) REFERENCES ESTANTES (CODESTANTE) ON DELETE SET NULL
);
ALTER TABLE RESENHAS 
	ADD CONSTRAINT CHECK_SPOIL
		CHECK (SPOILER IN
			('YES','NO')
		);


CREATE TABLE TAGS (
    CODTAG INTEGER NOT NULL,
    PALAVRA VARCHAR(40)  NOT NULL,
    CODUSUARIOCRIADOR VARCHAR(16) NOT NULL,
    PRIMARY KEY (CODTAG),
	FOREIGN KEY (CODUSUARIOCRIADOR) REFERENCES USUARIOS (CODUSUARIO)
);
ALTER TABLE TAGS ADD CONSTRAINT PALAVRA_UNIQUE
	UNIQUE (PALAVRA);
	

CREATE TABLE GENEROS (
    CODGENERO INTEGER NOT NULL,
    CATEGORIA VARCHAR(40) NOT NULL,
	PRIMARY KEY (CODGENERO)
);
ALTER TABLE GENEROS ADD CONSTRAINT CATEGORIA_UNIQUE
	UNIQUE (CATEGORIA);


CREATE TABLE AMIZADES (
    CODUSUARIO VARCHAR(16) NOT NULL,
    CODAMIGO VARCHAR(16) NOT NULL,
	DATA_INICIO DATE NOT NULL,
    PRIMARY KEY (CODAMIGO, CODUSUARIO),
	FOREIGN KEY (CODAMIGO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE,
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO) ON DELETE CASCADE
);	
	
CREATE TABLE MEMBROS (
    CODUSUARIO VARCHAR(16) NOT NULL,
    CODGRUPO INTEGER NOT NULL,
    PRIMARY KEY (CODGRUPO,CODUSUARIO),
	FOREIGN KEY (CODUSUARIO) REFERENCES USUARIOS (CODUSUARIO),
	FOREIGN KEY (CODGRUPO) REFERENCES GRUPOS (CODGRUPO)
);

CREATE TABLE ETAGS (
    ESTANTE INTEGER NOT NULL,
    TAG INTEGER NULL,
    PRIMARY KEY (TAG, ESTANTE),
	FOREIGN KEY (TAG) REFERENCES TAGS (CODTAG),
	FOREIGN KEY (ESTANTE) REFERENCES ESTANTES (CODESTANTE)
);

CREATE TABLE GTAGS (
    GRUPO INTEGER,
    TAG INTEGER,
    PRIMARY KEY (TAG, GRUPO),
	FOREIGN KEY (TAG) REFERENCES TAGS (CODTAG),
	FOREIGN KEY (GRUPO) REFERENCES GRUPOS (CODGRUPO)
);

CREATE TABLE GENEROSLIVRO (
    CODGENERO INTEGER NOT NULL,
    CODLIVRO INT NOT NULL,
    PRIMARY KEY (CODGENERO, CODLIVRO),
	FOREIGN KEY (CODGENERO) REFERENCES GENEROS (CODGENERO) ON DELETE CASCADE,
	FOREIGN KEY (CODLIVRO) REFERENCES LIVROS (CODLIVRO) ON DELETE CASCADE
);

CREATE TABLE GENEROSAUTOR (
    CODGENERO INTEGER NOT NULL,
    CODAUTOR INTEGER NOT NULL,
    PRIMARY KEY (CODGENERO, CODAUTOR),
	FOREIGN KEY (CODGENERO) REFERENCES GENEROS (CODGENERO) ON DELETE CASCADE,
	FOREIGN KEY (CODAUTOR) REFERENCES AUTORES (CODAUTOR) ON DELETE CASCADE
);


COMMIT;